
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain logistics)
    (:requirements :typing)
    (:types
        obj - object
        loc - object
        cit - object
        object
    )

    (:constants
        
    )

    (:predicates
        (package ?x1 - obj)
        (in-city ?x1 - loc ?x2 - cit)
        (truck ?x1 - obj)
        (airplane ?x1 - obj)
        (airport ?x1 - loc)
        (in ?x1 - obj ?x2 - obj)
        (city ?x1 - cit)
        (at ?x1 - obj ?x2 - loc)
        (location ?x1 - loc)
    )

    (:functions
        
    )

    

    
    (:action unload-airplane
     :parameters (?x0 - obj ?x1 - obj ?x2 - loc)
     :precondition (and (airplane ?x1) (package ?x0) (in ?x0 ?x1) (location ?x2))
     :effect (and
        (at ?x0 ?x2)
        (not (in ?x0 ?x1)))
    )


    (:action load-airplane
     :parameters (?x0 - obj ?x1 - obj ?x2 - loc)
     :precondition (and (location ?x2) (airplane ?x1) (package ?x0) (at ?x0 ?x2))
     :effect (and
        (in ?x0 ?x1)
        (not (at ?x0 ?x2)))
    )


    (:action load-truck
     :parameters (?x0 - obj ?x1 - obj ?x2 - loc)
     :precondition (and (location ?x2) (package ?x0) (truck ?x1) (at ?x1 ?x2))
     :effect (and
        (in ?x0 ?x1)
        (not (at ?x0 ?x2)))
    )


    (:action fly-airplane
     :parameters (?x0 - obj ?x1 - loc ?x2 - loc)
     :precondition (and (airplane ?x0) (airport ?x2))
     :effect (and
        (at ?x0 ?x2)
        (not (at ?x0 ?x1)))
    )


    (:action unload-truck
     :parameters (?x0 - obj ?x1 - obj ?x2 - loc)
     :precondition (and (truck ?x1) (package ?x0) (in ?x0 ?x1) (location ?x2))
     :effect (and
        (at ?x0 ?x2)
        (not (in ?x0 ?x1)))
    )


    (:action drive-truck
     :parameters (?x0 - obj ?x1 - loc ?x2 - loc ?x3 - cit)
     :precondition (and (truck ?x0) (in-city ?x2 ?x3) (city ?x3) (location ?x1))
     :effect (and
        (at ?x0 ?x2)
        (not (at ?x0 ?x1)))
    )

)